CREATE TABLE IF NOT EXISTS NETWORK_TBL (
    ID   INTEGER PRIMARY KEY AUTOINCREMENT
                 UNIQUE,
    NAME STRING  UNIQUE,
    VER  STRING
);

CREATE TABLE IF NOT EXISTS CLASS_TBL (
    ID   INTEGER PRIMARY KEY AUTOINCREMENT
                 UNIQUE,
    NAME STRING  UNIQUE,
    VER  STRING
);

CREATE TABLE IF NOT EXISTS DEVICE_TBL (
    ID       INTEGER PRIMARY KEY AUTOINCREMENT
                     UNIQUE,
    NAME     STRING  UNIQUE,
    CLASS_ID INTEGER REFERENCES CLASS_TBL (ID),
    NET_ID   INTEGER REFERENCES NETWORK_TBL (ID)
);

CREATE TABLE IF NOT EXISTS DATA_TBL (
    ID     INTEGER  PRIMARY KEY AUTOINCREMENT
                    UNIQUE,
    DEV_ID INTEGER  REFERENCES DEVICE_TBL (ID),
    POWER  REAL,
    ENERGY REAL,
    TIME   DATETIME DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS ACTIVE_SUBS_TBL (
    ID     INTEGER PRIMARY KEY AUTOINCREMENT
                   UNIQUE,
    DEV_ID INTEGER REFERENCES DEVICE_TBL (ID),
    SUB_ID STRING
);

CREATE INDEX IF NOT EXISTS MAIN_INDEX ON DATA_TBL (
    DEV_ID DESC,
    TIME DESC
);

CREATE INDEX IF NOT EXISTS DEV_NAME ON DEVICE_TBL (
    NAME ASC
);
