apps:
  - script   : ./services/Devicehive-service/service.js
    name     : 'DeviceHive-connector'
    watch    : true
  - script   : ./services/Database-service/service.js
    name     : 'database'
    watch    : true
